// 技术生成器：基于真实技术史，批量产出 ~1000 条技术并自动织依赖网
// 输出：assets/techs_extra.js  ->  const EXTRA_TECHS = [...]
// 依赖接线规则：每个技术只依赖「时间更早」的技术（同分类最近前驱 + 前提分类最近前驱），
// 从而保证整图是 DAG（无环）且全连通。

const fs = require("fs");
const path = require("path");

// ---- 可复现随机 ----
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rnd = mulberry32(20260825);
const pick = arr => arr[Math.floor(rnd() * arr.length)];
const rint = (a, b) => a + Math.floor(rnd() * (b - a + 1));

// ---- 分类元数据 ----
const CAT_DEF = {
  basic: "科学基础与方法", material: "材料", energy: "能源", manufact: "制造与工具",
  transport: "交通运载", info: "信息通信", life: "生命与医疗", build: "建筑建造", military: "军事"
};
// 每个分类的前提分类（用于跨类织网）
const PREREQ = {
  basic: ["language", "writing", "mathematics"],
  material: ["chemistry", "physics", "fire"],
  energy: ["physics", "chemistry", "fire"],
  manufact: ["material", "energy", "mathematics"],
  transport: ["manufact", "energy", "material"],
  info: ["material", "energy", "mathematics"],
  life: ["biology", "chemistry", "mathematics"],
  build: ["material", "manufact", "energy"],
  military: ["manufact", "energy", "material", "transport"]
};
// 每类默认应用词与角色短语
const DEF = {
  basic: { app: ["理论建模", "实验测量", "工程计算"], role: "奠定了描述与理解自然的基础框架" },
  material: { app: ["工具制造", "结构件", "电子器件"], role: "提供了制造一切器物所需的物质基底" },
  energy: { app: ["动力输出", "照明加热", "驱动系统"], role: "把能量转化为可被利用的形式" },
  manufact: { app: ["零件加工", "批量制造", "精密装配"], role: "使器物得以被高效制造与复制" },
  transport: { app: ["人员位移", "物资运输", "远程投送"], role: "扩展了人类移动与物流的边界" },
  info: { app: ["信息记录", "远程传输", "智能处理"], role: "加速了知识的存储、传播与计算" },
  life: { app: ["疾病治疗", "健康维持", "生命干预"], role: "改善了对生命过程的理解与干预能力" },
  build: { app: ["房屋营建", "桥梁隧道", "城市基础设施"], role: "塑造了人类聚居与工程的尺度" },
  military: { app: ["防御工事", "火力打击", "战略威慑"], role: "改变了冲突的形态、规模与成本" }
};

function eraOf(y) {
  if (y < -3500) return "prehistoric";
  if (y < -500) return "ancient";
  if (y < 500) return "classical";
  if (y < 1500) return "medieval";
  if (y < 1750) return "earlymodern";
  if (y < 1900) return "industrial";
  if (y < 1950) return "electrical";
  if (y < 2000) return "info";
  return "intelligent";
}
function dateOf(y) {
  if (y < 0) {
    const a = -y;
    if (a >= 10000) return `约 ${(a / 10000).toFixed(a % 10000 === 0 ? 0 : 1)} 万年前`;
    return `公元前 ${a} 年`;
  }
  return `${y} 年`;
}

// ---- 读取现有锚点（data.js 中的真实技术） ----
const dataSrc = fs.readFileSync(path.join(__dirname, "../assets/data.js"), "utf8");
const anchorRe = /id:"([^"]+)"[^}]*?category:"([^"]+)"[^}]*?year:(-?\d+)/g;
const anchors = [];
let mm;
while ((mm = anchorRe.exec(dataSrc))) anchors.push({ id: mm[1], cat: mm[2], year: parseInt(mm[3]) });
const existingIds = new Set(anchors.map(a => a.id));

// ---- 技术目录（真实技术，按时间排序；格式见下） ----
// 条目: [id, 名称, English, 年份, 可选依赖[], 可选角色]
const CAT = {
basic: [
  ["counting", "计数与 tallying", "Counting", -30000],
  ["numerals", "数字符号系统", "Numerical Notation", -3500],
  ["arithmetic", "算术", "Arithmetic", -3000],
  ["geometry_euclid", "几何学", "Geometry", -300],
  ["zero_concept", "零的概念", "Zero Concept", 500],
  ["positional", "位值制计数法", "Positional Notation", 600],
  ["algebra", "代数", "Algebra", 820],
  ["trigonometry", "三角学", "Trigonometry", 150],
  ["decimal", "十进制小数", "Decimal Fractions", 1200],
  ["negative_num", "负数", "Negative Numbers", 100],
  ["logarithms", "对数", "Logarithms", 1614],
  ["analytic_geom", "解析几何", "Analytic Geometry", 1637],
  ["calculus", "微积分", "Calculus", 1687],
  ["probability", "概率论", "Probability Theory", 1654],
  ["complex_num", "复数", "Complex Numbers", 1572],
  ["number_theory", "数论", "Number Theory", -300],
  ["lin_algebra", "线性代数", "Linear Algebra", 1858],
  ["diff_eq", "微分方程", "Differential Equations", 1690],
  ["fourier", "傅里叶分析", "Fourier Analysis", 1807],
  ["statistics", "统计学", "Statistics", 1809],
  ["noneuclid", "非欧几何", "Non-Euclidean Geometry", 1829],
  ["group_theory", "群论", "Group Theory", 1832],
  ["topology", "拓扑学", "Topology", 1860],
  ["set_theory", "集合论", "Set Theory", 1874],
  ["graph_theory", "图论", "Graph Theory", 1736],
  ["combinatorics", "组合数学", "Combinatorics", 1650],
  ["math_logic", "数理逻辑", "Mathematical Logic", 1854],
  ["tensor_calc", "张量 calculus", "Tensor Calculus", 1900],
  ["measure_theory", "测度论", "Measure Theory", 1902],
  ["kolmogorov", "公理化概率", "Axiomatic Probability", 1933],
  ["chaos", "混沌理论", "Chaos Theory", 1963],
  ["fractal", "分形几何", "Fractal Geometry", 1975],
  ["game_theory", "博弈论", "Game Theory", 1944],
  ["info_theory", "信息论", "Information Theory", 1948],
  ["category_theory", "范畴论", "Category Theory", 1945],
  ["numerical", "数值分析", "Numerical Analysis", 1950],
  ["optimization", "最优化/线性规划", "Optimization", 1947],
  ["knot_theory", "纽结理论", "Knot Theory", 1860],
  ["proof_theory", "证明论", "Proof Theory", 1900],
  ["lambda_calc", "λ演算", "Lambda Calculus", 1936],
  ["catastrophe", "突变理论", "Catastrophe Theory", 1960],
  ["celestial_mech", "天体力学", "Celestial Mechanics", 1687],
  ["classical_mech", "经典力学", "Classical Mechanics", 1687],
  ["lagrangian", "分析力学", "Analytical Mechanics", 1788],
  ["thermo", "热力学", "Thermodynamics", 1824],
  ["stat_mech", "统计力学", "Statistical Mechanics", 1872],
  ["em_theory", "电磁理论", "Electromagnetism", 1865],
  ["wave_optics", "波动光学", "Wave Optics", 1678],
  ["special_rel", "狭义相对论", "Special Relativity", 1905],
  ["general_rel", "广义相对论", "General Relativity", 1915],
  ["quantum_mech", "量子力学", "Quantum Mechanics", 1925],
  ["qft", "量子场论", "Quantum Field Theory", 1948],
  ["standard_model", "标准模型", "Standard Model", 1970],
  ["particle_phys", "粒子物理学", "Particle Physics", 1932],
  ["nuclear_phys", "核物理", "Nuclear Physics", 1911],
  ["atomic_theory", "原子论", "Atomic Theory", 1803],
  ["molecular_theory", "分子学说", "Molecular Theory", 1811],
  ["crystallography", "晶体学", "Crystallography", 1780],
  ["spectroscopy", "光谱学", "Spectroscopy", 1802],
  ["periodic_table", "元素周期律", "Periodic Table", 1869],
  ["valence", "化学键/价键", "Chemical Bonding", 1852],
  ["organic_chem", "有机化学", "Organic Chemistry", 1828],
  ["inorganic_chem", "无机化学", "Inorganic Chemistry", 1700],
  ["physical_chem", "物理化学", "Physical Chemistry", 1887],
  ["analytical_chem", "分析化学", "Analytical Chemistry", 1750],
  ["biochem", "生物化学", "Biochemistry", 1890],
  ["polymer_chem", "高分子化学", "Polymer Chemistry", 1900],
  ["electrochem", "电化学", "Electrochemistry", 1800],
  ["cell_theory", "细胞学说", "Cell Theory", 1838],
  ["germ_theory", "微生物致病说", "Germ Theory", 1861],
  ["bio_evolution", "进化论", "Evolution", 1859],
  ["genetics", "遗传学", "Genetics", 1865],
  ["dna_struct", "DNA 双螺旋", "DNA Structure", 1953],
  ["molecular_bio", "分子生物学", "Molecular Biology", 1953],
  ["microbiology", "微生物学", "Microbiology", 1670],
  ["immunology", "免疫学", "Immunology", 1798],
  ["neuroscience", "神经科学", "Neuroscience", 1890],
  ["ecology", "生态学", "Ecology", 1866],
  ["taxonomy", "生物分类学", "Taxonomy", 1735],
  ["heliocentrism", "日心说", "Heliocentrism", 1543],
  ["kepler_laws", "开普勒定律", "Kepler's Laws", 1609],
  ["radio_astron", "射电天文学", "Radio Astronomy", 1932],
  ["cosmology", "宇宙学", "Cosmology", 1920],
  ["bigbang", "大爆炸宇宙论", "Big Bang Theory", 1949],
  ["observ_astron", "实测天文学", "Observational Astronomy", 1600],
  ["telescope", "望远镜", "Telescope", 1608],
  ["microscope", "显微镜", "Microscope", 1590],
  ["peer_review", "同行评审制度", "Peer Review", 1665],
  ["replication", "可重复实验", "Replication", 1900],
  ["metrology", "计量学", "Metrology", 1790],
  ["standards_units", "标准单位制", "Standard Units", 1799],
  ["cartography", "制图学", "Cartography", -2500],
  ["surveying", "测量学", "Surveying", -2000],
  ["computer_sci", "计算机科学", "Computer Science", 1936],
  ["algorithm", "算法理论", "Algorithms", 825],
  ["complexity", "计算复杂性", "Complexity Theory", 1971],
  ["math_crypto", "数论密码", "Mathematical Cryptography", 1976],
  ["control_theory", "控制论", "Control Theory", 1948],
  ["systems_theory", "系统论", "Systems Theory", 1940],
  ["fluid_mech", "流体力学", "Fluid Mechanics", 1752],
  ["solid_mech", "固体力学", "Solid Mechanics", 1700],
  ["acoustics", "声学", "Acoustics", 1700],
  ["thermo_chem", "热化学", "Thermochemistry", 1840],
  ["photochemistry", "光化学", "Photochemistry", 1840],
  ["biophysics", "生物物理学", "Biophysics", 1900],
  ["genomics", "基因组学", "Genomics", 1977],
  ["proteomics", "蛋白质组学", "Proteomics", 1995],
  ["nanoscience", "纳米科学", "Nanoscience", 1980],
  ["materials_sci", "材料科学", "Materials Science", 1950],
  ["data_science", "数据科学", "Data Science", 2000],
  ["network_sci", "网络科学", "Network Science", 1998],
  ["cognition", "认知科学", "Cognitive Science", 1970]
],
material: [
  ["mat_copper", "红铜冶炼", "Copper Smelting", -5000],
  ["mat_bronze", "青铜合金", "Bronze Alloy", -3300],
  ["mat_brass", "黄铜", "Brass", -2000],
  ["mat_iron", "块炼铁", "Bloomery Iron", -1200],
  ["mat_wrought", "熟铁", "Wrought Iron", -1000],
  ["mat_castiron", "铸铁", "Cast Iron", -500],
  ["mat_steel2", "坩埚钢", "Crucible Steel", 500],
  ["mat_ductile", "球墨铸铁", "Ductile Iron", 1943],
  ["mat_malleable", "可锻铸铁", "Malleable Iron", 1722],
  ["mat_stainless", "不锈钢", "Stainless Steel", 1913],
  ["mat_manganese", "锰钢", "Manganese Steel", 1882],
  ["mat_toolsteel", "工具钢", "Tool Steel", 1868],
  ["mat_hss", "高速钢", "High-Speed Steel", 1900],
  ["mat_die", "模具钢", "Die Steel", 1900],
  ["mat_siliconsteel", "硅钢", "Silicon Steel", 1900],
  ["mat_alu", "铝冶炼", "Aluminium Smelting", 1825],
  ["mat_alalloy", "硬铝合金", "Duralumin", 1909],
  ["mat_tialloy", "钛合金", "Titanium Alloy", 1950],
  ["mat_mgalloy", "镁合金", "Magnesium Alloy", 1930],
  ["mat_nialloy", "镍合金", "Nickel Alloy", 1900],
  ["mat_zinc", "锌冶炼", "Zinc Smelting", -500],
  ["mat_lead", "铅冶炼", "Lead Smelting", -3000],
  ["mat_tin", "锡冶炼", "Tin Smelting", -3000],
  ["mat_mercury", "汞冶炼", "Mercury Smelting", -2000],
  ["mat_gold", "黄金加工", "Gold Working", -4000],
  ["mat_silver", "白银加工", "Silver Working", -4000],
  ["mat_platinum", "铂族金属", "Platinum Group", 1750],
  ["mat_tungsten", "钨", "Tungsten", 1783],
  ["mat_chromium", "铬", "Chromium", 1797],
  ["mat_manganese2", "锰", "Manganese", 1774],
  ["mat_cobalt", "钴", "Cobalt", 1735],
  ["mat_molybdenum", "钼", "Molybdenum", 1781],
  ["mat_vanadium", "钒", "Vanadium", 1801],
  ["mat_tantalum", "钽", "Tantalum", 1802],
  ["mat_niobium", "铌", "Niobium", 1864],
  ["mat_zirconium", "锆", "Zirconium", 1789],
  ["mat_beryllium", "铍", "Beryllium", 1798],
  ["mat_solder", "软钎料", "Solder", -3000],
  ["mat_babbitt", "巴氏合金", "Babbitt Metal", 1839],
  ["mat_woodmetal", "伍德合金", "Wood's Metal", 1860],
  ["mat_shapemem", "形状记忆合金", "Shape Memory Alloy", 1962],
  ["mat_metglass", "非晶合金", "Amorphous Alloy", 1960],
  ["mat_powder", "粉末冶金", "Powder Metallurgy", 1800],
  ["mat_sinter", "烧结", "Sintering", -3000],
  ["mat_forging", "锻造", "Forging", -3000],
  ["mat_casting", "铸造", "Casting", -3500],
  ["mat_rolling", "轧制", "Rolling", 1500],
  ["mat_drawing", "拉拔", "Wire Drawing", 1200],
  ["mat_extrusion", "挤压成形", "Extrusion", 1800],
  ["mat_heat", "热处理", "Heat Treatment", -1000],
  ["mat_quench", "淬火", "Quenching", -1000],
  ["mat_temper", "回火", "Tempering", -1000],
  ["mat_anneal", "退火", "Annealing", -1000],
  ["mat_carburize", "渗碳", "Carburizing", -500],
  ["mat_casehard", "表面硬化", "Case Hardening", 1800],
  ["mat_plating", "电镀", "Electroplating", 1805],
  ["mat_anodize", "阳极氧化", "Anodizing", 1923],
  ["mat_galv", "热浸镀锌", "Hot-Dip Galvanizing", 1742],
  ["mat_pottery", "陶器", "Pottery", -10000],
  ["mat_porcelain", "瓷器", "Porcelain", 600],
  ["mat_stoneware", "炻器", "Stoneware", -2000],
  ["mat_glass", "玻璃", "Glass", -2500],
  ["mat_flatglass", "平板玻璃", "Flat Glass", 100],
  ["mat_floatglass", "浮法玻璃", "Float Glass", 1952],
  ["mat_tempered", "钢化玻璃", "Tempered Glass", 1874],
  ["mat_opticalglass", "光学玻璃", "Optical Glass", 1600],
  ["mat_glassfiber", "玻璃纤维", "Glass Fiber", 1930],
  ["mat_cement", "水泥", "Cement", -3000],
  ["mat_concrete", "混凝土", "Concrete", -2000],
  ["mat_reconcrete", "钢筋混凝土", "Reinforced Concrete", 1849],
  ["mat_prestress", "预应力混凝土", "Prestressed Concrete", 1886],
  ["mat_refractory", "耐火材料", "Refractory", -1500],
  ["mat_sic", "碳化硅", "Silicon Carbide", 1891],
  ["mat_alumina", "氧化铝陶瓷", "Alumina Ceramic", 1900],
  ["mat_zirconia", "氧化锆陶瓷", "Zirconia Ceramic", 1920],
  ["mat_sin", "氮化硅陶瓷", "Silicon Nitride", 1950],
  ["mat_wc", "碳化钨", "Tungsten Carbide", 1923],
  ["mat_foamceramic", "泡沫陶瓷", "Foam Ceramic", 1970],
  ["mat_aerogel", "气凝胶", "Aerogel", 1931],
  ["mat_rubber", "天然橡胶", "Natural Rubber", -1500],
  ["mat_vulcan", "硫化橡胶", "Vulcanized Rubber", 1839],
  ["mat_phenolic", "酚醛树脂", "Phenolic Resin", 1907],
  ["mat_nylon", "尼龙", "Nylon", 1935],
  ["mat_pe", "聚乙烯", "Polyethylene", 1933],
  ["mat_pp", "聚丙烯", "Polypropylene", 1954],
  ["mat_pvc", "聚氯乙烯", "PVC", 1926],
  ["mat_ps", "聚苯乙烯", "Polystyrene", 1930],
  ["mat_ptfe", "聚四氟乙烯", "PTFE", 1938],
  ["mat_polyester", "聚酯", "Polyester", 1930],
  ["mat_pu", "聚氨酯", "Polyurethane", 1937],
  ["mat_epoxy", "环氧树脂", "Epoxy", 1936],
  ["mat_pmma", "有机玻璃", "PMMA", 1933],
  ["mat_sbr", "丁苯橡胶", "SBR", 1929],
  ["mat_nbr", "丁腈橡胶", "Nitrile Rubber", 1931],
  ["mat_silicone", "硅橡胶", "Silicone Rubber", 1940],
  ["mat_abs", "ABS 树脂", "ABS", 1948],
  ["mat_pc", "聚碳酸酯", "Polycarbonate", 1953],
  ["mat_pa", "聚酰胺", "Polyamide", 1938],
  ["mat_pi", "聚酰亚胺", "Polyimide", 1961],
  ["mat_peek", "聚醚醚酮", "PEEK", 1978],
  ["mat_cf", "碳纤维", "Carbon Fiber", 1958],
  ["mat_aramid", "芳纶", "Aramid", 1965],
  ["mat_uhmwpe", "超高分子量聚乙烯", "UHMWPE", 1950],
  ["mat_conductingpoly", "导电聚合物", "Conducting Polymer", 1977],
  ["mat_hydrogel", "水凝胶", "Hydrogel", 1960],
  ["mat_ge", "锗", "Germanium", 1886],
  ["mat_siliconw", "单晶硅", "Monocrystalline Silicon", 1918],
  ["mat_polysi", "多晶硅", "Polycrystalline Silicon", 1940],
  ["mat_gaas", "砷化镓", "Gallium Arsenide", 1960],
  ["mat_gan", "氮化镓", "Gallium Nitride", 1969],
  ["mat_sicsemi", "碳化硅半导体", "SiC Semiconductor", 1980],
  ["mat_gan2", "氧化锌半导体", "ZnO Semiconductor", 1935],
  ["mat_inp", "磷化铟", "Indium Phosphide", 1950],
  ["mat_ito", "透明导电膜", "ITO Film", 1907],
  ["mat_perovskite", "钙钛矿材料", "Perovskite", 1970],
  ["mat_orgsc", "有机半导体", "Organic Semiconductor", 1980],
  ["mat_graphene", "石墨烯", "Graphene", 2004],
  ["mat_2d", "二维材料", "2D Materials", 2004],
  ["mat_plywood", "胶合板", "Plywood", 1800],
  ["mat_cfrp", "碳纤维复合材料", "Carbon Fiber Composite", 1960],
  ["mat_frp", "玻璃钢", "FRP", 1930],
  ["mat_honeycomb", "蜂窝夹层", "Honeycomb Sandwich", 1940],
  ["mat_mmc", "金属基复合材料", "MMC", 1960],
  ["mat_cmc", "陶瓷基复合材料", "CMC", 1970],
  ["mat_ltsc", "低温超导", "Low-Temp Superconductor", 1911],
  ["mat_htsc", "高温超导", "High-Temp Superconductor", 1986],
  ["mat_ybco", "钇钡铜氧", "YBCO", 1987],
  ["mat_hydrogenstorage", "储氢合金", "Hydrogen Storage Alloy", 1970],
  ["mat_pcm", "相变材料", "Phase Change Material", 1960],
  ["mat_thermoelec", "热电材料", "Thermoelectric Material", 1821],
  ["mat_piezo", "压电材料", "Piezoelectric Material", 1880],
  ["mat_ferrite", "铁氧体", "Ferrite", 1909],
  ["mat_softmag", "非晶软磁", "Amorphous Soft Magnet", 1960],
  ["mat_selfheal", "自修复材料", "Self-Healing Material", 2000],
  ["mat_bioinspired", "仿生材料", "Bioinspired Material", 1990],
  ["mat_biomat", "生物材料", "Biomaterial", 1960],
  ["mat_degradable", "可降解材料", "Biodegradable Material", 1980],
  ["mat_stealth", "吸波隐身材料", "Radar-Absorbing Material", 1950],
  ["mat_insulation", "隔热材料", "Thermal Insulation", 1800],
  ["mat_foammetal", "泡沫金属", "Metal Foam", 1950],
  ["mat_blastfurnace", "高炉炼铁", "Blast Furnace", -500],
  ["mat_cupola", "冲天炉", "Cupola Furnace", 1800],
  ["mat_inductionmelt", "感应熔炼", "Induction Melting", 1800],
  ["mat_continuouscast", "连续铸造", "Continuous Casting", 1840],
  ["mat_esr", "电渣重熔", "Electroslag Remelting", 1940],
  ["mat_metal3dp", "金属 3D 打印", "Metal 3D Printing", 1990],
  ["mat_binderjet", "粘结剂喷射", "Binder Jetting", 1990],
  ["mat_ded", "定向能量沉积", "Directed Energy Deposition", 1990],
  ["mat_coldspray", "冷喷涂", "Cold Spray", 1980],
  ["mat_thermalspray", "热喷涂", "Thermal Spray", 1900],
  ["mat_hvof", "超音速火焰喷涂", "HVOF", 1980],
  ["mat_laserclad", "激光熔覆", "Laser Cladding", 1980],
  ["mat_nitriding", "渗氮", "Nitriding", 1900],
  ["mat_boriding", "渗硼", "Boriding", 1900],
  ["mat_ebm", "电子束熔融", "Electron Beam Melting", 1990],
  ["mat_sps", "放电等离子烧结", "Spark Plasma Sintering", 1960],
  ["mat_mof", "金属有机框架", "Metal-Organic Framework", 1990],
  ["mat_zeolite", "沸石分子筛", "Zeolite", 1700]
],
energy: [
  ["ene_charcoal", "木炭", "Charcoal", -4000],
  ["ene_coal", "煤炭开采", "Coal Mining", -1000],
  ["ene_coke", "焦炭", "Coke", 1700],
  ["ene_oil", "石油开采", "Oil Extraction", 1850],
  ["ene_natgas", "天然气利用", "Natural Gas", 1820],
  ["ene_oilshale", "油页岩", "Oil Shale", 1800],
  ["ene_biofuel", "生物燃料", "Biofuel", 1800],
  ["ene_ethanol", "燃料乙醇", "Ethanol Fuel", 1850],
  ["ene_biodiesel", "生物柴油", "Biodiesel", 1890],
  ["ene_biomass", "生物质气化", "Biomass Gasification", 1800],
  ["ene_hydro", "水力利用", "Hydropower", -3000],
  ["ene_waterwheel", "水车", "Water Wheel", -300],
  ["ene_waterturbine", "水轮机", "Water Turbine", 1820],
  ["ene_wind", "风车", "Windmill", 900],
  ["ene_windturbine", "风力发电机", "Wind Turbine", 1887],
  ["ene_geothermal", "地热利用", "Geothermal", 1800],
  ["ene_tidal", "潮汐能", "Tidal Power", 1960],
  ["mat_wave", "波浪能", "Wave Energy", 1970],
  ["ene_solarthermal", "太阳能热利用", "Solar Thermal", 1700],
  ["ene_pv", "光伏电池", "Photovoltaic", 1954],
  ["ene_csp", "聚光太阳能", "Concentrated Solar", 1980],
  ["ene_steamturbine", "蒸汽轮机", "Steam Turbine", 1884],
  ["ene_gasturbine", "燃气轮机", "Gas Turbine", 1939],
  ["ene_stirling", "斯特林发动机", "Stirling Engine", 1816],
  ["ene_jet", "喷气发动机", "Jet Engine", 1937],
  ["ene_rocketengine", "火箭发动机", "Rocket Engine", 1926],
  ["ene_leadacid", "铅酸电池", "Lead-Acid Battery", 1859],
  ["ene_nicd", "镍镉电池", "NiCd Battery", 1899],
  ["ene_nimh", "镍氢电池", "NiMH Battery", 1989],
  ["ene_liion", "锂离子电池", "Li-ion Battery", 1991],
  ["ene_lipoly", "锂聚合物电池", "Li-Po Battery", 1996],
  ["ene_nas", "钠离子电池", "Sodium-Ion Battery", 2010],
  ["ene_solidstate", "固态电池", "Solid-State Battery", 2010],
  ["ene_fuelcell", "燃料电池", "Fuel Cell", 1839],
  ["ene_h2fc", "氢燃料电池", "Hydrogen Fuel Cell", 1960],
  ["ene_zincair", "锌空气电池", "Zinc-Air Battery", 1932],
  ["ene_flow", "液流电池", "Flow Battery", 1970],
  ["ene_supercap", "超级电容", "Supercapacitor", 1957],
  ["ene_flywheel", "飞轮储能", "Flywheel Storage", 1950],
  ["ene_pumped", "抽水蓄能", "Pumped Storage", 1890],
  ["ene_caes", "压缩空气储能", "CAES", 1949],
  ["ene_molten", "熔盐储热", "Molten Salt Storage", 1980],
  ["ene_h2storage", "储氢技术", "Hydrogen Storage", 1970],
  ["ene_transformer", "变压器", "Transformer", 1885],
  ["ene_transmission", "电力传输", "Power Transmission", 1882],
  ["ene_ac", "交流电系统", "AC Power", 1888],
  ["ene_dc", "直流电系统", "DC Power", 1800],
  ["ene_smartgrid", "智能电网", "Smart Grid", 2000],
  ["ene_nuclear", "核裂变反应堆", "Nuclear Reactor", 1942],
  ["ene_pwr", "压水堆", "PWR", 1953],
  ["ene_bwr", "沸水堆", "BWR", 1955],
  ["ene_phwr", "重水堆", "PHWR", 1960],
  ["ene_fastbreeder", "快中子增殖堆", "Fast Breeder", 1951],
  ["ene_fusion", "核聚变", "Nuclear Fusion", 1950],
  ["ene_tokamak", "托卡马克", "Tokamak", 1968],
  ["ene_icf", "惯性约束聚变", "Inertial Confinement", 1960],
  ["ene_satpower", "空间太阳能", "Space Solar Power", 1968],
  ["ene_wpt", "无线输电", "Wireless Power", 1890],
  ["ene_thermoelectric", "热电发电", "Thermoelectric Generation", 1821],
  ["ene_piezoelectric", "压电发电", "Piezoelectric Harvesting", 1880],
  ["ene_tribo", "摩擦纳米发电", "Triboelectric Nanogen", 2012],
  ["ene_biogenic", "生物发电", "Bioelectric Generation", 1800],
  ["ene_synfuel", "合成燃料", "Syngas Fuel", 1920],
  ["ene_ammonia", "氨燃料", "Ammonia Fuel", 1900],
  ["ene_clathrate", "可燃冰", "Methane Hydrate", 1960],
  ["ene_hotdry", "干热岩", "Hot Dry Rock", 1970],
  ["ene_otec", "海洋温差能", "OTEC", 1881],
  ["ene_salinity", "盐差能", "Salinity Gradient", 1950],
  ["ene_methanol", "甲醇燃料", "Methanol Fuel", 1900],
  ["ene_hydrogenfuel", "氢燃料", "Hydrogen Fuel", 1800],
  ["ene_coalfired", "燃煤发电", "Coal Power Plant", 1882],
  ["ene_gasfired", "燃气发电", "Gas Power Plant", 1900],
  ["ene_hydroplant", "水力发电站", "Hydroelectric Plant", 1882],
  ["ene_windfarm", "风电场", "Wind Farm", 1980],
  ["ene_solarfarm", "光伏电站", "Solar Farm", 1980],
  ["ene_batteryev", "电池储能系统", "Battery Energy Storage", 1990],
  ["ene_microgrid", "微电网", "Microgrid", 2000],
  ["ene_v2g", "车网互动", "Vehicle-to-Grid", 2000],
  ["ene_heatpump", "热泵", "Heat Pump", 1852],
  ["ene_district", "区域供冷供热", "District Energy", 1877],
  ["ene_wasteheat", "余热回收", "Waste Heat Recovery", 1800],
  ["ene_fuelcellcar", "燃料电池汽车", "Fuel Cell Vehicle", 1990],
  ["ene_peaker", "调峰电站", "Peaker Plant", 1900],
  ["ene_island", "离网供电", "Off-Grid System", 2000],
  ["ene_bess", "集装箱储能", "BESS Container", 2010],
  ["ene_gravity", "重力储能", "Gravity Storage", 2000],
  ["ene_liquidair", "液态空气储能", "Liquid Air Storage", 2010],
  ["ene_thermalbattery", "热电池", "Thermal Battery", 1980],
  ["ene_bipv", "光伏建筑一体化", "BIPV", 2000],
  ["ene_solartower", "熔盐塔式光热", "Solar Power Tower", 1980],
  ["ene_dishstirling", "碟式斯特林", "Dish-Stirling", 1980],
  ["ene_linearfresnel", "线性菲涅尔", "Linear Fresnel", 2000],
  ["ene_hydrothermal", "水热型地热", "Hydrothermal Geothermal", 1970],
  ["ene_borehole", "井式地热", "Borehole Geothermal", 2000]
],
manufact: [
  ["mfg_stone", "石器打制", "Stone Knapping", -2600000],
  ["mfg_handaxe", "手斧", "Hand Axe", -1700000],
  ["mfg_knife", "刀具", "Knife", -100000],
  ["mfg_chisel", "凿", "Chisel", -30000],
  ["mfg_hammer", "锤", "Hammer", -50000],
  ["mfg_axe", "斧", "Axe", -50000],
  ["mfg_saw", "锯", "Saw", -5000],
  ["mfg_drill", "钻", "Drill", -10000],
  ["mfg_lathe", "车床", "Lathe", -1000],
  ["mfg_boring", "镗床", "Boring Machine", 1500],
  ["mfg_mill", "铣床", "Milling Machine", 1818],
  ["mfg_planer", "刨床", "Planer", 1810],
  ["mfg_grinder", "磨床", "Grinder", 1800],
  ["mfg_drillpress", "钻床", "Drill Press", 1800],
  ["mfg_cnc", "数控机床", "CNC Machine", 1949],
  ["mfg_mc", "加工中心", "Machining Center", 1958],
  ["mfg_turnmill", "车铣复合", "Turn-Mill", 1980],
  ["mfg_3dp", "3D 打印", "3D Printing", 1984],
  ["mfg_additive", "增材制造", "Additive Manufacturing", 1986],
  ["mfg_lasercut", "激光切割", "Laser Cutting", 1965],
  ["mfg_waterjet", "水射流切割", "Water Jet Cutting", 1970],
  ["mfg_plasma", "等离子切割", "Plasma Cutting", 1950],
  ["mfg_edm", "电火花加工", "EDM", 1943],
  ["mfg_wedm", "线切割", "Wire EDM", 1960],
  ["mfg_sandcast", "砂型铸造", "Sand Casting", -3500],
  ["mfg_lostwax", "失蜡法", "Lost-Wax Casting", -3500],
  ["mfg_diecast", "压铸", "Die Casting", 1838],
  ["mfg_forging2", "模锻", "Die Forging", 1800],
  ["mfg_stamping", "冲压", "Stamping", 1800],
  ["mfg_drawing2", "拉伸成形", "Deep Drawing", 1800],
  ["mfg_rivet", "铆接", "Riveting", -2000],
  ["mfg_welding", "电弧焊", "Arc Welding", 1881],
  ["mfg_gasweld", "气焊", "Gas Welding", 1900],
  ["mfg_resistweld", "电阻焊", "Resistance Welding", 1877],
  ["mfg_laserweld", "激光焊", "Laser Welding", 1960],
  ["mfg_fsw", "搅拌摩擦焊", "Friction Stir Welding", 1991],
  ["mfg_ebw", "电子束焊", "Electron Beam Welding", 1958],
  ["mfg_braze", "钎焊", "Brazing", -2000],
  ["mfg_adhesive", "胶接", "Adhesive Bonding", -2000],
  ["mfg_bolt", "螺纹连接", "Bolting", -300],
  ["mfg_thread", "螺纹", "Screw Thread", -300],
  ["mfg_standard", "零件标准化", "Part Standardization", 1800],
  ["mfg_assembly", "装配线", "Assembly Line", 1900],
  ["mfg_fixture", "工装夹具", "Jig and Fixture", 1800],
  ["mfg_mold", "模具", "Mold", -3000],
  ["mfg_injection", "注塑", "Injection Molding", 1872],
  ["mfg_blow", "吹塑", "Blow Molding", 1930],
  ["mfg_extrude2", "挤出成型", "Extrusion Molding", 1800],
  ["mfg_rolling2", "压延", "Rolling Forming", 1500],
  ["mfg_wiredraw", "拉丝", "Wire Drawing", 1200],
  ["mfg_furnace", "热处理炉", "Heat Treatment Furnace", 1800],
  ["mfg_vacfurnace", "真空炉", "Vacuum Furnace", 1950],
  ["mfg_induction", "感应加热", "Induction Heating", 1887],
  ["mfg_shotblast", "喷丸", "Shot Peening", 1930],
  ["mfg_polish", "抛光", "Polishing", -3000],
  ["mfg_lapp", "研磨", "Lapping", -3000],
  ["mfg_ultraprecise", "超精密加工", "Ultra-Precision Machining", 1960],
  ["mfg_micro", "微细加工", "Microfabrication", 1950],
  ["mfg_nanoimprint", "纳米压印", "Nanoimprint", 1995],
  ["mfg_ecm", "电解加工", "Electrochemical Machining", 1950],
  ["mfg_chemill", "化学铣切", "Chemical Milling", 1940],
  ["mfg_pim", "金属注射成形", "Metal Injection Molding", 1970],
  ["mfg_hip", "热等静压", "Hot Isostatic Pressing", 1955],
  ["mfg_cmm", "三坐标测量", "CMM", 1950],
  ["mfg_reverse", "逆向工程", "Reverse Engineering", 1980],
  ["mfg_plc", "可编程逻辑控制器", "PLC", 1968],
  ["mfg_servo", "伺服系统", "Servo System", 1940],
  ["mfg_ballscrew", "滚珠丝杠", "Ball Screw", 1898],
  ["mfg_linearmotor", "直线电机", "Linear Motor", 1940],
  ["mfg_harmonic", "谐波减速器", "Harmonic Drive", 1955],
  ["mfg_precisionbearing", "精密轴承", "Precision Bearing", 1883],
  ["mfg_gauge", "量具", "Gauge", -2000],
  ["mfg_spcc", "统计过程控制", "SPC", 1924],
  ["mfg_sixsigma", "六西格玛", "Six Sigma", 1986],
  ["mfg_lean", "精益生产", "Lean Production", 1950],
  ["mfg_kanban", "看板管理", "Kanban", 1940],
  ["mfg_cam", "计算机辅助制造", "CAM", 1970],
  ["mfg_fms", "柔性制造系统", "FMS", 1967],
  ["mfg_adaptive", "自适应控制", "Adaptive Control", 1950],
  ["mfg_digitaltwin", "数字孪生", "Digital Twin", 2000],
  ["mfg_cobot", "协作机器人", "Collaborative Robot", 1996],
  ["mfg_selfassemble", "自组装", "Self-Assembly", 1990],
  ["mfg_bionics", "仿生制造", "Biomimetic Manufacturing", 1990],
  ["mfg_grindingwheel", "砂轮", "Grinding Wheel", 1840],
  ["mfg_abrasive", "磨料", "Abrasive", -5000],
  ["mfg_toolholder", "刀柄", "Tool Holder", 1900],
  ["mfg_coolant", "切削液", "Cutting Fluid", 1900],
  ["mfg_edmwire", "电火花线切割机", "Wire EDM Machine", 1960],
  ["mfg_roboticweld", "焊接机器人", "Welding Robot", 1980],
  ["mfg_agv", "自动导引车", "AGV", 1953],
  ["mfg_aps", "高级计划排程", "APS", 1990],
  ["mfg_quality", "全面质量管理", "TQM", 1950],
  ["mfg_mes", "制造执行系统", "MES", 1990],
  ["mfg_industry40", "工业 4.0", "Industry 4.0", 2011],
  ["mfg_ecmg", "电解磨削", "Electrochemical Grinding", 1960],
  ["mfg_ultrasonicm", "超声加工", "Ultrasonic Machining", 1950],
  ["mfg_awj", "磨料水射流", "Abrasive Water Jet", 1980],
  ["mfg_hybridm", "增减材混合制造", "Hybrid Manufacturing", 2010],
  ["mfg_toolmonitor", "刀具状态监控", "Tool Monitoring", 1990],
  ["mfg_cryogenicm", "低温切削", "Cryogenic Machining", 2000],
  ["mfg_onmachinem", "在机测量", "On-Machine Measurement", 1990],
  ["mfg_robotgripper", "机器人夹爪", "Robot Gripper", 1980],
  ["mfg_visionguide", "视觉引导装配", "Vision-Guided Assembly", 2000],
  ["mfg_digitalshop", "数字化车间", "Digital Shopfloor", 2010],
  ["mfg_darkfactory", "无人化工厂", "Lights-Out Factory", 2010]
],
transport: [
  ["tr_canoe", "独木舟", "Canoe", -10000],
  ["tr_raft", "木筏", "Raft", -10000],
  ["tr_paddle", "桨", "Paddle", -8000],
  ["tr_sail", "帆船", "Sailing Ship", -3500],
  ["tr_paddlesteamer", "明轮船", "Paddle Steamer", 1800],
  ["tr_steamship", "蒸汽船", "Steamship", 1807],
  ["tr_screwprop", "螺旋桨", "Screw Propeller", 1836],
  ["tr_submarine", "潜艇", "Submarine", 1620],
  ["tr_balloon", "热气球", "Hot-Air Balloon", 1783],
  ["tr_airship", "飞艇", "Airship", 1852],
  ["tr_glider", "滑翔机", "Glider", 1853],
  ["tr_helicopter", "直升机", "Helicopter", 1939],
  ["tr_jetliner", "喷气客机", "Jet Airliner", 1952],
  ["tr_supersonic", "超音速客机", "Supersonic Transport", 1969],
  ["tr_autogyro", "旋翼机", "Autogyro", 1923],
  ["tr_rocket", "运载火箭", "Launch Vehicle", 1926],
  ["tr_shuttle", "航天飞机", "Space Shuttle", 1981],
  ["tr_station", "空间站", "Space Station", 1971],
  ["tr_hsr", "高速铁路", "High-Speed Rail", 1964],
  ["tr_maglev", "磁悬浮列车", "Maglev", 1984],
  ["tr_metro", "地铁", "Metro", 1863],
  ["tr_tram", "有轨电车", "Tram", 1832],
  ["tr_trolley", "无轨电车", "Trolleybus", 1882],
  ["tr_bus", "公共汽车", "Bus", 1895],
  ["tr_truck", "卡车", "Truck", 1896],
  ["tr_motorcycle", "摩托车", "Motorcycle", 1885],
  ["tr_bicycle", "自行车", "Bicycle", 1817],
  ["tr_train", "铁路列车", "Railway Train", 1804],
  ["tr_steamloco", "蒸汽机车", "Steam Locomotive", 1814],
  ["tr_diesel loco", "内燃机车", "Diesel Locomotive", 1912],
  ["tr_emu", "动车组", "EMU", 1900],
  ["tr_cablecar", "缆车", "Cable Car", 1800],
  ["tr_ropeway", "索道", "Aerial Ropeway", 1600],
  ["tr_elevator", "电梯", "Elevator", 1852],
  ["tr_escalator", "自动扶梯", "Escalator", 1891],
  ["tr_crane", "起重机", "Crane", -300],
  ["tr_forklift", "叉车", "Forklift", 1917],
  ["tr_bulldozer", "推土机", "Bulldozer", 1923],
  ["tr_excavator", "挖掘机", "Excavator", 1830],
  ["tr_loader", "装载机", "Loader", 1920],
  ["tr_tractor", "拖拉机", "Tractor", 1892],
  ["tr_combine", "联合收割机", "Combine Harvester", 1834],
  ["tr_aircraftcarrier", "航空母舰", "Aircraft Carrier", 1917],
  ["tr_destroyer", "驱逐舰", "Destroyer", 1890],
  ["tr_cruiser", "巡洋舰", "Cruiser", 1800],
  ["tr_icebreaker", "破冰船", "Icebreaker", 1957],
  ["tr_dredger", "挖泥船", "Dredger", 1800],
  ["tr_hovercraft", "气垫船", "Hovercraft", 1956],
  ["tr_ekranoplan", "地效飞行器", "Ground Effect Vehicle", 1960],
  ["tr_jetpack", "喷气背包", "Jet Pack", 1950],
  ["tr_hoverboard", "平衡车", "Hoverboard", 2013],
  ["tr_skateboard", "滑板", "Skateboard", 1950],
  ["tr_sled", "雪橇", "Sled", -5000],
  ["tr_stirrup", "马镫", "Stirrup", 300],
  ["tr_horseshoe", "马蹄铁", "Horseshoe", 300],
  ["tr_pneumatictire", "充气轮胎", "Pneumatic Tire", 1845],
  ["tr_solidtire", "实心轮胎", "Solid Tire", 1800],
  ["tr_track", "履带", "Track", 1770],
  ["tr_suspension", "悬挂系统", "Suspension", 1800],
  ["tr_steering", "转向系统", "Steering", 1800],
  ["tr_brake", "制动系统", "Braking", 1800],
  ["tr_abs", "防抱死制动", "ABS", 1978],
  ["tr_navigation", "航海导航", "Marine Navigation", -2000],
  ["tr_autopilot", "自动驾驶仪", "Autopilot", 1912],
  ["tr_trafficsignal", "交通信号灯", "Traffic Light", 1868],
  ["tr_lighthouse", "灯塔", "Lighthouse", -1000],
  ["tr_radar2", "雷达", "Radar", 1935],
  ["tr_transponder", "应答机", "Transponder", 1940],
  ["tr_blackbox", "飞行记录器", "Black Box", 1950],
  ["tr_simulator", "飞行模拟器", "Flight Simulator", 1910],
  ["tr_windtunnel", "风洞", "Wind Tunnel", 1871],
  ["tr_runway", "机场跑道", "Runway", 1900],
  ["tr_port", "港口", "Port", -3000],
  ["tr_canal", "运河", "Canal", -4000],
  ["tr_suez", "苏伊士运河", "Suez Canal", 1869],
  ["tr_panama", "巴拿马运河", "Panama Canal", 1914],
  ["tr_tunnel2", "交通隧道", "Traffic Tunnel", 1700],
  ["tr_interchange", "立交桥", "Interchange", 1900],
  ["tr_servicearea", "服务区", "Service Area", 1920],
  ["tr_gasstation", "加油站", "Gas Station", 1900],
  ["tr_charging", "充电站", "Charging Station", 2000],
  ["tr_v2x", "车路协同", "V2X", 2010],
  ["tr_containership", "集装箱船", "Container Ship", 1956],
  ["tr_bulktanker", "油轮", "Oil Tanker", 1860],
  ["tr_roship", "滚装船", "Ro-Ro Ship", 1900],
  ["tr_ferry", "渡轮", "Ferry", -3000],
  ["tr_hsrbridge", "高铁桥梁", "HSR Bridge", 1900],
  ["tr_monorail", "单轨铁路", "Monorail", 1900],
  ["tr_funicular", "齿轨铁路", "Funicular", 1800],
  ["tr_pipeline", "管道运输", "Pipeline Transport", 1800],
  ["tr_hyperloop", "真空管道列车", "Hyperloop", 2013],
  ["tr_evcar", "电动汽车", "Electric Car", 1990],
  ["tr_fcevtruck", "燃料电池卡车", "Fuel Cell Truck", 2010],
  ["tr_personalair", "个人飞行器", "Personal Aerial Vehicle", 2010],
  ["tr_electricboat", "电动船", "Electric Boat", 1990],
  ["tr_auv", "自主水下航行器", "AUV", 1960],
  ["tr_rov", "遥控潜水器", "ROV", 1950],
  ["tr_cargo_drone", "无人机货运", "Cargo Drone", 2010],
  ["tr_passdrone", "载人无人机", "Passenger Drone", 2010],
  ["tr_hypersonic", "高超声速飞行", "Hypersonic Flight", 2000],
  ["tr_reusablerocket", "可回收火箭", "Reusable Rocket", 2015],
  ["tr_lunarlander", "月球着陆器", "Lunar Lander", 1960]
],
info: [
  ["inf_pencil", "铅笔", "Pencil", 1795],
  ["inf_pen", "钢笔", "Fountain Pen", 1884],
  ["inf_ballpoint", "圆珠笔", "Ballpoint Pen", 1938],
  ["inf_typewriter", "打字机", "Typewriter", 1868],
  ["inf_carbonpaper", "复写纸", "Carbon Paper", 1800],
  ["inf_mimeograph", "油印", "Mimeograph", 1870],
  ["inf_photocopier", "复印机", "Photocopier", 1938],
  ["inf_fax", "传真机", "Fax", 1843],
  ["inf_telegraph", "电报", "Telegraph", 1837],
  ["inf_telephone", "电话", "Telephone", 1876],
  ["inf_switchboard", "电话交换机", "Telephone Exchange", 1878],
  ["inf_cable", "通信电缆", "Communication Cable", 1850],
  ["inf_submarine_cable", "海底电缆", "Submarine Cable", 1858],
  ["inf_radio2", "无线电广播", "Radio Broadcasting", 1906],
  ["inf_tv", "电视", "Television", 1927],
  ["inf_bw_tv", "黑白电视", "Black-White TV", 1927],
  ["inf_color_tv", "彩色电视", "Color TV", 1953],
  ["inf_vcr", "录像机", "VCR", 1956],
  ["inf_camcorder", "摄像机", "Camcorder", 1980],
  ["inf_vinyl", "黑胶唱片", "Vinyl Record", 1877],
  ["inf_tape", "磁带", "Magnetic Tape", 1928],
  ["inf_microprocessor", "微处理器", "Microprocessor", 1971],
  ["inf_ram", "内存", "RAM", 1947],
  ["inf_hdd", "硬盘", "Hard Disk", 1956],
  ["inf_floppy", "软盘", "Floppy Disk", 1971],
  ["inf_flash", "闪存", "Flash Memory", 1980],
  ["inf_usb", "U 盘", "USB Drive", 2000],
  ["inf_ssd", "固态硬盘", "SSD", 1991],
  ["inf_os", "操作系统", "Operating System", 1950],
  ["inf_compiler", "编译器", "Compiler", 1952],
  ["inf_pl_fortran", "Fortran", "Fortran", 1957],
  ["inf_pl_c", "C 语言", "C Language", 1972],
  ["inf_pl_python", "Python", "Python", 1991],
  ["inf_db", "数据库", "Database", 1960],
  ["inf_rdbms", "关系型数据库", "RDBMS", 1970],
  ["inf_sql", "SQL", "SQL", 1974],
  ["inf_nosql", "NoSQL", "NoSQL", 2000],
  ["inf_search", "搜索引擎", "Search Engine", 1990],
  ["inf_browser", "网页浏览器", "Web Browser", 1990],
  ["inf_email", "电子邮件", "Email", 1971],
  ["inf_im", "即时通讯", "Instant Messaging", 1996],
  ["inf_social", "社交网络", "Social Network", 2000],
  ["inf_wifi", "Wi-Fi", "Wi-Fi", 1997],
  ["inf_bluetooth", "蓝牙", "Bluetooth", 1994],
  ["inf_5g", "5G", "5G", 2018],
  ["inf_6g", "6G", "6G", 2020],
  ["inf_fiber", "光纤通信", "Fiber Optics Comms", 1970],
  ["inf_microwave", "微波中继", "Microwave Relay", 1940],
  ["inf_modem", "调制解调器", "Modem", 1958],
  ["inf_router", "路由器", "Router", 1980],
  ["inf_net_switch", "网络交换机", "Network Switch", 1980],
  ["inf_lan", "局域网", "LAN", 1970],
  ["inf_wan", "广域网", "WAN", 1970],
  ["inf_vpn", "虚拟专网", "VPN", 1996],
  ["inf_blockchain", "区块链", "Blockchain", 2008],
  ["inf_pubkey", "公钥密码", "Public-Key Crypto", 1976],
  ["inf_symenc", "对称加密", "Symmetric Crypto", 1949],
  ["inf_hash", "哈希函数", "Hash Function", 1953],
  ["inf_digitalsig", "数字签名", "Digital Signature", 1976],
  ["inf_qrcode", "二维码", "QR Code", 1994],
  ["inf_barcode", "条形码", "Barcode", 1948],
  ["inf_rfid", "射频识别", "RFID", 1948],
  ["inf_sensor_net", "无线传感网", "WSN", 1980],
  ["inf_iot", "物联网", "IoT", 1999],
  ["inf_edge", "边缘计算", "Edge Computing", 2000],
  ["inf_cloud", "云计算", "Cloud Computing", 2000],
  ["inf_fog", "雾计算", "Fog Computing", 2010],
  ["inf_quantumcom", "量子通信", "Quantum Communication", 1980],
  ["inf_qkd", "量子密钥分发", "QKD", 1984],
  ["inf_ml", "机器学习", "Machine Learning", 1959],
  ["inf_dl", "深度学习", "Deep Learning", 2006],
  ["inf_nn", "神经网络", "Neural Network", 1958],
  ["inf_expert", "专家系统", "Expert System", 1965],
  ["inf_knowledge", "知识图谱", "Knowledge Graph", 2007],
  ["inf_nlp", "自然语言处理", "NLP", 1950],
  ["inf_asr", "语音识别", "Speech Recognition", 1952],
  ["inf_mt", "机器翻译", "Machine Translation", 1954],
  ["inf_recommend", "推荐系统", "Recommender", 1990],
  ["inf_ar", "增强现实", "Augmented Reality", 1990],
  ["inf_vr", "虚拟现实", "Virtual Reality", 1980],
  ["inf_bigdata", "大数据", "Big Data", 2000],
  ["inf_dataviz", "数据可视化", "Data Visualization", 1980],
  ["inf_gis", "地理信息系统", "GIS", 1960],
  ["inf_emap", "电子地图", "Digital Map", 1980],
  ["inf_navsoft", "导航软件", "Navigation Software", 1990],
  ["inf_watermark", "数字水印", "Digital Watermark", 1990],
  ["inf_steg", "信息隐藏", "Steganography", 1990],
  ["inf_ecc", "纠错码", "Error Correction Code", 1949],
  ["inf_compression", "数据压缩", "Data Compression", 1950],
  ["inf_codec", "编解码", "Codec", 1950],
  ["inf_modulation", "调制技术", "Modulation", 1900],
  ["inf_antenna", "天线", "Antenna", 1888],
  ["inf_phasedarray", "相控阵", "Phased Array", 1930],
  ["inf_sdn", "软件定义网络", "SDN", 2000],
  ["inf_container", "容器技术", "Container", 2000],
  ["inf_microservice", "微服务", "Microservice", 2010],
  ["inf_lowcode", "低代码", "Low-Code", 2010],
  ["inf_devops", "DevOps", "DevOps", 2010],
  ["inf_cicd", "持续集成", "CI/CD", 2010],
  ["inf_agile", "敏捷开发", "Agile", 2001],
  ["inf_uml", "统一建模语言", "UML", 1997],
  ["inf_git", "版本控制", "Version Control", 1972],
  ["inf_api", "应用程序接口", "API", 2000],
  ["inf_middleware", "中间件", "Middleware", 1990],
  ["inf_cdn", "内容分发网络", "CDN", 1990],
  ["inf_loadbalancer", "负载均衡", "Load Balancer", 1990],
  ["inf_cache", "缓存系统", "Caching", 1990],
  ["inf_graphdb", "图数据库", "Graph Database", 2000],
  ["inf_timeseries", "时序数据库", "Time-Series DB", 2000],
  ["inf_vector_db", "向量数据库", "Vector Database", 2010],
  ["inf_recommend2", "协同过滤", "Collaborative Filtering", 1992],
  ["inf_transformer", "Transformer 架构", "Transformer", 2017],
  ["inf_llm", "大语言模型", "LLM", 2018],
  ["inf_diffusion", "扩散模型", "Diffusion Model", 2015],
  ["inf_rl", "强化学习", "Reinforcement Learning", 1950],
  ["inf_gan", "生成对抗网络", "GAN", 2014],
  ["inf_rpa", "机器人流程自动化", "RPA", 2010],
  ["inf_alloptical", "全光网络", "All-Optical Network", 2000],
  ["inf_400g", "高速光模块", "High-Speed Optical Module", 2010],
  ["inf_leo", "低轨卫星星座", "LEO Constellation", 2010],
  ["inf_quantuminternet", "量子互联网", "Quantum Internet", 2020],
  ["inf_homomorphic", "同态加密", "Homomorphic Encryption", 2009],
  ["inf_zeroknowledge", "零知识证明", "Zero-Knowledge Proof", 1985],
  ["inf_multimodal", "多模态大模型", "Multimodal Model", 2020],
  ["inf_agent", "智能体", "AI Agent", 2020],
  ["inf_worldmodel", "世界模型", "World Model", 2020],
  ["inf_embedding", "嵌入模型", "Embedding Model", 2010],
  ["inf_vectorsearch", "向量检索", "Vector Search", 2010],
  ["inf_rag", "检索增强生成", "RAG", 2020],
  ["inf_alignment", "大模型对齐", "AI Alignment", 2020],
  ["inf_speechsyn", "语音合成", "Speech Synthesis", 1990],
  ["inf_digitalhuman", "数字人", "Digital Human", 2020],
  ["inf_edgeai", "边缘智能", "Edge AI", 2015],
  ["inf_aisearch", "AI 搜索", "AI Search", 2020],
  ["inf_codegen", "代码生成模型", "Code Generation", 2020]
],
life: [
  ["bio_herb", "草药学", "Herbal Medicine", -5000],
  ["bio_acupuncture", "针灸", "Acupuncture", -2000],
  ["bio_anatomy", "解剖学", "Anatomy", -300],
  ["bio_physiology", "生理学", "Physiology", -300],
  ["bio_pharmacology", "药理学", "Pharmacology", 1800],
  ["bio_prescription", "方剂学", "Prescriptions", -2000],
  ["bio_distill", "蒸馏制药", "Distilled Medicine", 800],
  ["bio_aspirin", "阿司匹林", "Aspirin", 1897],
  ["bio_penicillin", "青霉素", "Penicillin", 1928],
  ["bio_antibiotic", "抗生素", "Antibiotics", 1928],
  ["bio_smallpox", "牛痘接种", "Smallpox Vaccination", 1796],
  ["bio_bcg", "卡介苗", "BCG Vaccine", 1921],
  ["bio_insulin", "胰岛素", "Insulin", 1921],
  ["bio_hormone", "激素疗法", "Hormone Therapy", 1900],
  ["bio_vitamin", "维生素", "Vitamin", 1912],
  ["bio_transfusion", "输血", "Blood Transfusion", 1818],
  ["bio_bloodtype", "血型", "Blood Group", 1901],
  ["bio_anesthesia", "麻醉", "Anesthesia", 1846],
  ["bio_aseptic", "无菌术", "Aseptic Technique", 1867],
  ["bio_surgery", "外科学", "Surgery", -500],
  ["bio_suture", "缝合", "Suturing", -2000],
  ["bio_orthopedics", "骨科", "Orthopedics", 1800],
  ["bio_neurosurgery", "神经外科", "Neurosurgery", 1900],
  ["bio_cardiovascular", "心血管外科", "Cardiovascular Surgery", 1900],
  ["bio_transplant", "器官移植", "Organ Transplant", 1954],
  ["bio_dialysis", "血液透析", "Dialysis", 1943],
  ["bio_artkidney", "人工肾", "Artificial Kidney", 1943],
  ["bio_pacemaker", "心脏起搏器", "Pacemaker", 1958],
  ["bio_stent", "血管支架", "Stent", 1980],
  ["bio_endoscope", "内窥镜", "Endoscope", 1800],
  ["bio_laparoscope", "腹腔镜", "Laparoscope", 1900],
  ["bio_ultrasound", "超声诊断", "Medical Ultrasound", 1950],
  ["bio_ct", "CT 扫描", "CT Scan", 1971],
  ["bio_mri", "核磁共振", "MRI", 1973],
  ["bio_xray", "X 射线", "X-Ray", 1895],
  ["bio_nuclear_med", "核医学", "Nuclear Medicine", 1950],
  ["bio_pet", "正电子成像", "PET", 1970],
  ["bio_seq", "基因测序", "DNA Sequencing", 1977],
  ["bio_pcr", "聚合酶链反应", "PCR", 1983],
  ["bio_crispr", "基因编辑", "CRISPR", 2012],
  ["bio_transgenic", "转基因", "Transgenics", 1973],
  ["bio_clone", "克隆技术", "Cloning", 1996],
  ["bio_ivf", "试管婴儿", "IVF", 1978],
  ["bio_stemcell", "干细胞", "Stem Cell", 1963],
  ["bio_tissueeng", "组织工程", "Tissue Engineering", 1980],
  ["bio_artskin", "人工皮肤", "Artificial Skin", 1980],
  ["bio_prosthesis", "假肢", "Prosthesis", -2000],
  ["bio_hearingaid", "助听器", "Hearing Aid", 1898],
  ["bio_glasses", "眼镜", "Eyeglasses", 1280],
  ["bio_contactlens", "隐形眼镜", "Contact Lens", 1888],
  ["bio_iol", "人工晶体", "Intraocular Lens", 1949],
  ["bio_denture", "义齿", "Denture", -500],
  ["bio_dentistry", "牙科", "Dentistry", -3000],
  ["bio_epidemiology", "流行病学", "Epidemiology", 1800],
  ["bio_disinfectant", "消毒剂", "Disinfectant", 1800],
  ["bio_probiotic", "益生菌", "Probiotics", 1900],
  ["bio_nutrition", "营养学", "Nutrition", 1800],
  ["bio_enzyme", "酶工程", "Enzyme Engineering", 1950],
  ["bio_fermentation", "发酵工程", "Fermentation Engineering", 1900],
  ["bio_bioreactor", "生物反应器", "Bioreactor", 1940],
  ["bio_monoclonal", "单克隆抗体", "Monoclonal Antibody", 1975],
  ["bio_interferon", "干扰素", "Interferon", 1957],
  ["bio_mrnavax", "mRNA 疫苗", "mRNA Vaccine", 1990],
  ["bio_antiviral", "抗病毒药", "Antiviral", 1960],
  ["bio_chemo", "化学治疗", "Chemotherapy", 1900],
  ["bio_radiotherapy", "放射治疗", "Radiotherapy", 1900],
  ["bio_targeted", "靶向治疗", "Targeted Therapy", 1990],
  ["bio_immunotherapy", "免疫治疗", "Immunotherapy", 2010],
  ["bio_genetherapy", "基因治疗", "Gene Therapy", 1990],
  ["bio_celltherapy", "细胞治疗", "Cell Therapy", 2000],
  ["bio_cart", "CAR-T 疗法", "CAR-T", 2010],
  ["bio_bloodprod", "血液制品", "Blood Products", 1940],
  ["bio_ivd", "体外诊断", "IVD", 1950],
  ["bio_poc", "快速检测", "POCT", 1980],
  ["bio_wearable", "可穿戴健康", "Wearable Health", 2000],
  ["bio_telemed", "远程医疗", "Telemedicine", 1950],
  ["bio_ehr", "电子病历", "EHR", 1970],
  ["bio_medicalai", "医疗影像 AI", "Medical Imaging AI", 2010],
  ["bio_surgerobot", "手术机器人", "Surgical Robot", 2000],
  ["bio_reharobot", "康复机器人", "Rehabilitation Robot", 2000],
  ["bio_exoskeleton", "外骨骼", "Exoskeleton", 2000],
  ["bio_bci", "脑机接口", "BCI", 1970],
  ["bio_neuromod", "神经调控", "Neuromodulation", 1980],
  ["bio_dbs", "深部脑刺激", "DBS", 1987],
  ["bio_bioniceye", "仿生眼", "Bionic Eye", 2000],
  ["bio_cochlear", "人工耳蜗", "Cochlear Implant", 1977],
  ["bio_bio3dp", "生物 3D 打印", "Bioprinting", 2000],
  ["bio_organoid", "类器官", "Organoid", 2009],
  ["bio_synbio", "合成生物学", "Synthetic Biology", 2000],
  ["bio_directedevo", "定向进化", "Directed Evolution", 1990],
  ["bio_proteineng", "蛋白质工程", "Protein Engineering", 1980],
  ["bio_metabeng", "代谢工程", "Metabolic Engineering", 1990],
  ["bio_microbiome", "微生物组", "Microbiome", 2000],
  ["bio_phage", "噬菌体疗法", "Phage Therapy", 1920],
  ["bio_drugdelivery", "药物递送", "Drug Delivery", 1950],
  ["bio_nanomed", "纳米药物", "Nanomedicine", 2000],
  ["bio_sustained", "缓释制剂", "Sustained Release", 1950],
  ["bio_transdermal", "透皮给药", "Transdermal", 1970],
  ["bio_inhaler", "吸入制剂", "Inhaler", 1950],
  ["bio_genevector", "基因递送载体", "Gene Vector", 1970],
  ["bio_lipidnp", "脂质纳米粒", "LNP", 2000],
  ["bio_vaccineplatform", "疫苗平台", "Vaccine Platform", 2000],
  ["bio_pathogen", "病原体鉴定", "Pathogen ID", 1800],
  ["bio_epigenetics", "表观遗传学", "Epigenetics", 1980],
  ["bio_proteomics2", "蛋白组学", "Proteomics", 1995],
  ["bio_metabolomics", "代谢组学", "Metabolomics", 2000],
  ["bio_spatialtrans", "空间转录组", "Spatial Transcriptomics", 2010],
  ["bio_singlecell", "单细胞测序", "Single-Cell Sequencing", 2009],
  ["bio_organonchip", "器官芯片", "Organs-on-Chip", 2010],
  ["bio_universalvax", "通用疫苗", "Universal Vaccine", 2020],
  ["bio_newantibiotic", "新型抗生素", "Novel Antibiotic", 2000],
  ["bio_antimicrobialpep", "抗菌肽", "Antimicrobial Peptide", 2000],
  ["bio_precisionmed", "精准医疗", "Precision Medicine", 2010],
  ["bio_pharmacogen", "药物基因组学", "Pharmacogenomics", 2000],
  ["bio_liquidbiopsy", "液体活检", "Liquid Biopsy", 2010],
  ["bio_ctdna", "循环肿瘤 DNA", "ctDNA", 2010],
  ["bio_cgm", "连续血糖监测", "CGM", 2010],
  ["bio_ecmo", "体外膜肺氧合", "ECMO", 1972],
  ["bio_artliver", "人工肝", "Artificial Liver", 1990],
  ["bio_artlung", "人工肺", "Artificial Lung", 1990],
  ["bio_arthroplasty", "人工关节", "Artificial Joint", 1960]
],
build: [
  ["bld_rammed", "夯土", "Rammed Earth", -10000],
  ["bld_adobe", "土坯砖", "Adobe", -9000],
  ["bld_brick", "烧砖", "Fired Brick", -5000],
  ["bld_tile", "瓦", "Roof Tile", -3000],
  ["bld_timber", "木构建筑", "Timber Frame", -5000],
  ["bld_mortise", "榫卯", "Mortise and Tenon", -5000],
  ["bld_dougong", "斗拱", "Dougong Bracket", -500],
  ["bld_stone", "石构建筑", "Stone Construction", -3000],
  ["bld_arch", "拱", "Arch", -1000],
  ["bld_dome", "穹顶", "Dome", -100],
  ["bld_ribvault", "肋拱", "Rib Vault", 1100],
  ["bld_flying", "飞扶壁", "Flying Buttress", 1100],
  ["bld_gothic", "哥特结构", "Gothic Structure", 1100],
  ["bld_romanconc", "罗马混凝土", "Roman Concrete", -100],
  ["bld_framing", "框架结构", "Frame Structure", 1800],
  ["bld_shearwall", "剪力墙", "Shear Wall", 1900],
  ["bld_tube", "筒体结构", "Tube Structure", 1960],
  ["bld_cablestay", "斜拉桥", "Cable-Stayed Bridge", 1955],
  ["bld_suspension", "悬索桥", "Suspension Bridge", 1800],
  ["bld_truss", "桁架", "Truss", 1800],
  ["bld_steelbridge", "钢桥", "Steel Bridge", 1800],
  ["bld_tunnel3", "隧道掘进", "Tunnel Boring", 1800],
  ["bld_shield", "盾构法", "Shield Tunnelling", 1825],
  ["bld_immersed", "沉管隧道", "Immersed Tunnel", 1890],
  ["bld_pile", "桩基础", "Pile Foundation", -2000],
  ["bld_raftfound", "筏基", "Raft Foundation", 1800],
  ["bld_ground", "地基处理", "Ground Improvement", 1800],
  ["bld_grouting", "灌浆", "Grouting", 1800],
  ["bld_waterproof", "防水", "Waterproofing", 1800],
  ["bld_insulation2", "保温隔热", "Thermal Insulation", 1800],
  ["bld_curtain", "玻璃幕墙", "Curtain Wall", 1950],
  ["bld_daylight", "自然采光", "Daylighting", 1800],
  ["bld_vent", "通风系统", "Ventilation", 1800],
  ["bld_hvac", "空调系统", "HVAC", 1900],
  ["bld_plumbing", "给排水", "Plumbing", 1800],
  ["bld_sewage", "污水处理", "Sewage Treatment", 1800],
  ["bld_rainwater", "雨水管理", "Stormwater Mgmt", 1900],
  ["bld_fireprotect", "消防系统", "Fire Protection", 1800],
  ["bld_sprinkler", "自动喷淋", "Sprinkler", 1874],
  ["bld_lightning", "避雷", "Lightning Protection", 1700],
  ["bld_seismic", "抗震设计", "Seismic Design", 1900],
  ["bld_isolation", "隔震", "Seismic Isolation", 1970],
  ["bld_modular", "模块化建筑", "Modular Building", 1900],
  ["bld_precast", "预制构件", "Precast", 1900],
  ["bld_prefab", "装配式建筑", "Prefabrication", 1900],
  ["bld_3dpb", "3D 打印建筑", "3D Printed Building", 2010],
  ["bld_green", "绿色建筑", "Green Building", 1990],
  ["bld_passive", "被动房", "Passive House", 1990],
  ["bld_zeroenergy", "零能耗建筑", "Zero-Energy Building", 2000],
  ["bld_smartb", "智能建筑", "Smart Building", 2000],
  ["bld_bim", "建筑信息模型", "BIM", 1970],
  ["bld_survey2", "工程测量", "Engineering Survey", 1800],
  ["bld_underground", "地下空间", "Underground Space", 1800],
  ["bld_sponge", "海绵城市", "Sponge City", 2000],
  ["bld_verticalgreen", "垂直绿化", "Vertical Greening", 1990],
  ["bld_geothermal2", "地源热泵建筑", "Geothermal Building", 1980],
  ["bld_towercrane", "塔吊", "Tower Crane", 1900],
  ["bld_pump", "混凝土泵车", "Concrete Pump", 1920],
  ["bld_climbform", "爬模", "Climbing Form", 1960],
  ["bld_aluform", "铝模板", "Aluminium Formwork", 1980],
  ["bld_robotbrick", "砌砖机器人", "Bricklaying Robot", 2010],
  ["bld_dronesurvey", "无人机测绘", "Drone Surveying", 2015],
  ["bld_smartcity", "智慧城市", "Smart City", 2010],
  ["bld_variabletbm", "可变径盾构", "Variable-Diameter TBM", 2010],
  ["bld_frpbridge", "复材桥梁", "FRP Bridge", 2010],
  ["bld_3dconcrete", "混凝土 3D 打印", "Concrete 3D Printing", 2015],
  ["bld_selfhealconc", "自修复混凝土", "Self-Healing Concrete", 2010],
  ["bld_carbonconc", "碳纤维混凝土", "Carbon Concrete", 2010]
],
military: [
  ["mil_bow", "弓", "Bow", -20000],
  ["mil_arrow", "箭", "Arrow", -20000],
  ["mil_crossbow", "弩", "Crossbow", -1000],
  ["mil_catapult", "投石机", "Catapult", -400],
  ["mil_javelin", "标枪", "Javelin", -20000],
  ["mil_spear", "长矛", "Spear", -20000],
  ["mil_sword", "剑", "Sword", -3000],
  ["mil_shield", "盾", "Shield", -3000],
  ["mil_armor", "盔甲", "Armor", -3000],
  ["mil_chainmail", "锁子甲", "Chainmail", -500],
  ["mil_plate", "板甲", "Plate Armor", 1300],
  ["mil_matchlock", "火绳枪", "Matchlock", 1500],
  ["mil_fintlock", "燧发枪", "Flintlock", 1600],
  ["mil_musket", "滑膛枪", "Musket", 1500],
  ["mil_rifle", "来复枪", "Rifle", 1800],
  ["mil_machinegun", "机枪", "Machine Gun", 1884],
  ["mil_submachine", "冲锋枪", "Submachine Gun", 1918],
  ["mil_sniper", "狙击步枪", "Sniper Rifle", 1800],
  ["mil_pistol", "手枪", "Pistol", 1500],
  ["mil_revolver", "左轮手枪", "Revolver", 1836],
  ["mil_artillery", "火炮", "Artillery", 1200],
  ["mil_blackpowder", "黑火药", "Black Powder", 800],
  ["mil_smokeless", "无烟火药", "Smokeless Powder", 1884],
  ["mil_dynamite", "炸药", "Dynamite", 1867],
  ["mil_ng", "硝化甘油", "Nitroglycerin", 1847],
  ["mil_tnt", "TNT", "TNT", 1863],
  ["mil_detonator", "雷管", "Detonator", 1863],
  ["mil_landmine", "地雷", "Landmine", 1200],
  ["mil_seamine", "水雷", "Naval Mine", 1800],
  ["mil_grenade", "手榴弹", "Grenade", 1400],
  ["mil_rocket2", "火箭弹", "Rocket Projectile", 1200],
  ["mil_missile", "导弹", "Missile", 1944],
  ["mil_ballistic", "弹道导弹", "Ballistic Missile", 1942],
  ["mil_cruise", "巡航导弹", "Cruise Missile", 1950],
  ["mil_sam", "防空导弹", "SAM", 1950],
  ["mil_atgm", "反坦克导弹", "ATGM", 1960],
  ["mil_guidance", "制导技术", "Guidance", 1940],
  ["mil_inertial", "惯性制导", "Inertial Guidance", 1950],
  ["mil_laserguid", "激光制导", "Laser Guidance", 1960],
  ["mil_irguid", "红外制导", "IR Guidance", 1950],
  ["mil_phasedradar", "相控阵雷达", "Phased Array Radar", 1960],
  ["mil_sonar", "声纳", "Sonar", 1917],
  ["mil_nightvision", "夜视仪", "Night Vision", 1930],
  ["mil_thermal", "热成像", "Thermal Imaging", 1950],
  ["mil_recon", "侦察技术", "Reconnaissance", 1800],
  ["mil_loitering", "巡飞弹", "Loitering Munition", 1980],
  ["mil_ew", "电子战", "Electronic Warfare", 1900],
  ["mil_jamming", "干扰", "Jamming", 1900],
  ["mil_stealth2", "隐身技术", "Stealth Tech", 1970],
  ["mil_lowobs", "低可探测", "Low Observability", 1970],
  ["mil_tank", "坦克", "Tank", 1916],
  ["mil_apc", "装甲运兵车", "APC", 1918],
  ["mil_spg", "自行火炮", "Self-Propelled Gun", 1930],
  ["mil_mrl", "火箭炮", "MLRS", 1930],
  ["mil_howitzer", "榴弹炮", "Howitzer", 1700],
  ["mil_cannon", "加农炮", "Cannon", 1200],
  ["mil_aagun", "高射炮", "AA Gun", 1900],
  ["mil_torpedo", "鱼雷", "Torpedo", 1866],
  ["mil_depthcharge", "深水炸弹", "Depth Charge", 1910],
  ["mil_nuclearsub", "核潜艇", "Nuclear Submarine", 1954],
  ["mil_frigate", "护卫舰", "Frigate", 1700],
  ["mil_ssbn", "战略导弹潜艇", "SSBN", 1959],
  ["mil_bomber", "战略轰炸机", "Strategic Bomber", 1940],
  ["mil_fighter", "战斗机", "Fighter Aircraft", 1915],
  ["mil_aewc", "预警机", "AWACS", 1970],
  ["mil_tankerac", "空中加油机", "Tanker Aircraft", 1920],
  ["mil_transportac", "军用运输机", "Military Transport", 1920],
  ["mil_airborne", "空降兵", "Airborne Troops", 1940],
  ["mil_bodyarmor", "防弹衣", "Body Armor", 1500],
  ["mil_kevlar2", "凯夫拉护具", "Kevlar Protection", 1970],
  ["mil_helmet", "钢盔", "Combat Helmet", 1914],
  ["mil_cbrn", "三防装备", "CBRN Protection", 1940],
  ["mil_c4isr", "指挥控制系统", "C4ISR", 1980],
  ["mil_satrec", "卫星侦察", "Satellite Recon", 1960],
  ["mil_aweapon", "原子弹", "Atomic Bomb", 1945],
  ["mil_hweapon", "氢弹", "Hydrogen Bomb", 1952],
  ["mil_neutron", "中子弹", "Neutron Bomb", 1960],
  ["mil_triad", "核三位一体", "Nuclear Triad", 1960],
  ["mil_missiledef", "导弹防御", "Missile Defense", 1980],
  ["mil_cyber", "网络战", "Cyber Warfare", 1990],
  ["mil_psyop", "心理战", "Psychological Warfare", 1900],
  ["mil_logistics", "军事后勤", "Military Logistics", 1800],
  ["mil_fieldhospital", "战地医疗", "Field Hospital", 1800],
  ["mil_engineer", "工程兵", "Combat Engineer", -2000],
  ["mil_mineclear", "扫雷", "Mine Clearing", 1900],
  ["mil_assaultbridge", "舟桥", "Assault Bridge", 1800],
  ["mil_camo", "伪装迷彩", "Camouflage", 1800],
  ["mil_decoy", "假目标", "Decoy", 1900],
  ["mil_loyalwingman", "忠诚僚机", "Loyal Wingman", 2020],
  ["mil_swarm", "无人机蜂群", "Drone Swarm", 2010],
  ["mil_aiwar", "军事人工智能", "Military AI", 2010],
  ["mil_directedenergy", "定向能武器", "Directed Energy Weapon", 1980],
  ["mil_laserw", "激光武器", "Laser Weapon", 1980],
  ["mil_hpm", "高功率微波武器", "HPM Weapon", 1990],
  ["mil_railgun", "电磁轨道炮", "Railgun", 2000],
  ["mil_hypersonicm", "高超声速导弹", "Hypersonic Missile", 2010],
  ["mil_glider", "高超滑翔体", "Hypersonic Glide Vehicle", 2010],
  ["mil_smartmunition", "智能弹药", "Smart Munition", 2010]
]
};

module.exports = { CAT, anchors, existingIds, CAT_DEF, PREREQ, DEF, eraOf, dateOf };

// ---- 主生成逻辑（仅在直接运行时执行） ----
if (require.main === module) {
  const gen = require("./gen_run");
  gen.run();
}
